/**
 * probe.mjs - measure what ONE emitted exception-unwind release costs in
 * shipped .text, by building a family of programs and reading the slope.
 *
 * The emitted C re-materialises the whole live set's release list at every
 * fallible call site. Source bytes say that is 38.7% of the emitted C for
 * zapo; source bytes are not machine code, so this measures the machine
 * code directly:
 *
 *   size(K live locals, N fallible calls) = a + b*N + c*K*N
 *
 * b is what one call site costs with an empty live set (the guard, the
 * call, the return). c is what ONE release in ONE epilogue costs. Sweeping
 * K at fixed N and N at fixed K gives both, and the residual of the fit is
 * printed so a model that does not describe the data cannot be quoted.
 *
 * Each program is generated so that every call is FALLIBLE (it can throw)
 * and every local is live across every call (used after the last one).
 *
 * Usage: node probe.mjs --out <scratch dir> --k 2,4,8,16 --n 200
 */
import { writeFileSync, mkdirSync, statSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { pathToFileURL } from 'node:url'
import { peSections } from './attrib.mjs'

export function genProgram(K, N) {
  const L = []
  L.push('// generated by probe.mjs - K=' + K + ' N=' + N)
  L.push('function boom(s: string): string {')
  L.push('  if (s.length > 1000000) throw new Error("no");')
  L.push('  return s + "x";')
  L.push('}')
  L.push('export function probe(seed: string): number {')
  for (let k = 0; k < K; k++) L.push('  const v' + k + ' = seed + "' + k + '";')
  for (let n = 0; n < N; n++) L.push('  const r' + n + ' = boom(seed + "' + n + '");')
  // keep every local live to the end
  L.push('  let acc = 0;')
  for (let k = 0; k < K; k++) L.push('  acc += v' + k + '.length;')
  for (let n = 0; n < N; n++) L.push('  acc += r' + n + '.length;')
  L.push('  return acc;')
  L.push('}')
  L.push('console.log(String(probe("s")));')
  return L.join('\n') + '\n'
}

function fmt(n) { return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',') }

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const argv = process.argv.slice(2)
  const flag = (n, d = null) => { const i = argv.indexOf('--' + n); return i < 0 ? d : argv[i + 1] }
  const outDir = flag('out')
  if (!outDir) { console.error('--out <dir> is required (a scratch directory; never C:)'); process.exit(2) }
  const Ks = (flag('k', '1,4,8,16')).split(',').map(Number)
  const Ns = (flag('n', '50,100,200')).split(',').map(Number)
  const cli = flag('cli', new URL('../../../packages/cli/dist/main.js', import.meta.url).pathname.replace(/^\//, ''))
  mkdirSync(outDir, { recursive: true })

  const rows = []
  for (const K of Ks) for (const N of Ns) {
    const stem = 'p' + K + '_' + N
    const ts = outDir + '/' + stem + '.ts'
    const exe = outDir + '/' + stem + '.exe'
    writeFileSync(ts, genProgram(K, N), 'utf8')
    try { rmSync(exe) } catch { /* first run */ }
    const t0 = Date.now()
    execFileSync(process.execPath, [cli, 'build', ts, '--backend', 'c', '--keep-c', '-o', exe],
      { cwd: outDir, stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, SCRIPTC_NO_CACHE: '1' } })
    const pe = peSections(exe)
    const size = pe.sections.find((s) => s.name === '.text').vsize
    const csize = statSync(outDir + '/' + stem + '.c').size
    rows.push({ K, N, size, csize, ms: Date.now() - t0 })
    console.log('K=' + String(K).padStart(3) + ' N=' + String(N).padStart(4) +
      '  .text ' + fmt(size).padStart(10) + '  c ' + fmt(csize).padStart(11) + '  ' + (Date.now() - t0) + 'ms')
  }

  // least squares on size = a + b*N + c*K*N
  const X = rows.map((r) => [1, r.N, r.K * r.N])
  const y = rows.map((r) => r.size)
  const p = 3
  const A = Array.from({ length: p }, () => new Array(p).fill(0))
  const bv = new Array(p).fill(0)
  for (let i = 0; i < X.length; i++) {
    for (let a = 0; a < p; a++) {
      bv[a] += X[i][a] * y[i]
      for (let b2 = 0; b2 < p; b2++) A[a][b2] += X[i][a] * X[i][b2]
    }
  }
  // gaussian elimination
  for (let c = 0; c < p; c++) {
    let piv = c
    for (let r2 = c + 1; r2 < p; r2++) if (Math.abs(A[r2][c]) > Math.abs(A[piv][c])) piv = r2
    ;[A[c], A[piv]] = [A[piv], A[c]]; [bv[c], bv[piv]] = [bv[piv], bv[c]]
    for (let r2 = 0; r2 < p; r2++) {
      if (r2 === c) continue
      const f = A[r2][c] / A[c][c]
      for (let k2 = c; k2 < p; k2++) A[r2][k2] -= f * A[c][k2]
      bv[r2] -= f * bv[c]
    }
  }
  const coef = bv.map((v, i) => v / A[i][i])
  console.log('')
  console.log('fit  size = a + b*N + c*K*N')
  console.log('  a (fixed)                 ' + coef[0].toFixed(1))
  console.log('  b (bytes per call site)   ' + coef[1].toFixed(2))
  console.log('  c (bytes per release)     ' + coef[2].toFixed(3))
  let ss = 0, sm = 0
  const ybar = y.reduce((s, v) => s + v, 0) / y.length
  for (let i = 0; i < X.length; i++) {
    const pred = coef[0] + coef[1] * X[i][1] + coef[2] * X[i][2]
    ss += (y[i] - pred) ** 2; sm += (y[i] - ybar) ** 2
    console.log('  K=' + String(rows[i].K).padStart(3) + ' N=' + String(rows[i].N).padStart(4) +
      '  actual ' + fmt(y[i]).padStart(10) + '  pred ' + fmt(Math.round(pred)).padStart(10) +
      '  resid ' + fmt(Math.round(y[i] - pred)).padStart(9))
  }
  console.log('  R^2 ' + (1 - ss / sm).toFixed(5))
  console.log('  measured on .text VirtualSize read from the PE section table: byte-exact, no file alignment.')
}
