export TMP='<blocks>\mediavoip\tmp'
export TEMP='<blocks>\mediavoip\tmp'
export TMPDIR='<blocks>\mediavoip\tmp'
export SCRIPTC_CACHE_DIR='<blocks>\mediavoip\cache'
export SCRIPTC_PROVENANCE_CACHE='<blocks>\mediavoip\cache\provenance'
export ZIG_GLOBAL_CACHE_DIR='<blocks>\mediavoip\zig'
export ZIG_LOCAL_CACHE_DIR='<blocks>\mediavoip\zig\local'
export SCRIPTC_CC=zigcc
export SCRIPTC_TEST_CC="zig cc"
export SCRIPTC_TARGET=x86_64-windows-gnu
export SCRIPTC_TEST_WORKERS=2
export WT='<blocks>/mediavoip/wt'
export LAB='<blocks>/mediavoip/lab'
export ZPKG='<zapo-work>/caches/provenance/250f9af5229a545eec28ddbd3e8774a397cdb0bb/packages'
export PATH="<zapo-work>/tools/zig:$PATH"
