/* Generated by scriptc from <blocks>/wamcoord-lab/napp/amb1.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static SCR_STR_LIT(2) sc_lit_0 =
    { SCR_STR_IMMORTAL, 1, 1, "s" };
static SCR_STR_LIT(3) sc_lit_1 =
    { SCR_STR_IMMORTAL, 2, 2, "a=" };
static SCR_STR_LIT(2) sc_lit_2 =
    { SCR_STR_IMMORTAL, 1, 1, "a" };

static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_main(void);

static void sc_f__x25_init_0(void) { /* <blocks>/wamcoord-lab/napp/amb1.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* <blocks>/wamcoord-lab/napp/amb1.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* <blocks>/wamcoord-lab/napp/amb1.ts:1 */
  ScrStr *sc_t2 = (ScrStr *)&sc_lit_0;
  double sc_t3 = (scr_undef_global_read(sc_t2), 0);
  if (scr_exc_pending()) {
    return;
  }
  ScrStr *sc_t4 = (ScrStr *)&sc_lit_1;
  ScrStr *sc_t5 = (ScrStr *)&sc_lit_2;
  ScrStr *sc_t6 = (scr_undef_global_read(sc_t5), (ScrStr *)NULL);
  if (scr_exc_pending()) {
    scr_str_release(sc_t6);
    return;
  }
  ScrStr *sc_t7 = scr_str_concat(sc_t4, sc_t6);
  ScrLogArg sc_t8[1];
  sc_t8[0].tag = SCR_ARG_STR; sc_t8[0].v.s = sc_t7;
  scr_console_log(1, sc_t8); /* <blocks>/wamcoord-lab/napp/amb1.ts:3 */
  scr_str_release(sc_t6);
  scr_str_release(sc_t7);
}

static void sc_f__x25_main(void) { /* <blocks>/wamcoord-lab/napp/amb1.ts:1 */
  sc_f__x25_init_0(); /* <blocks>/wamcoord-lab/napp/amb1.ts:1 */
  if (scr_exc_pending()) {
    return;
  }
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 5; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_error_vts[5].pre = 5; scr_error_vts[5].post = 5; /* ReferenceError */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  if (scr_exc_pending()) {
    scr_exc_print_uncaught();
    return 1;
  }
  /* no refcounted globals */
  return 0;
}
