export TMP='<blocks>\remeasure\tmp'
export TEMP='<blocks>\remeasure\tmp'
export TMPDIR='<blocks>\remeasure\tmp'
export SCRIPTC_CACHE_DIR='<blocks>\remeasure\cache'
export SCRIPTC_PROVENANCE_CACHE='<blocks>\remeasure\prov'
export ZIG_GLOBAL_CACHE_DIR='<blocks>\remeasure\zig'
export ZIG_LOCAL_CACHE_DIR='<blocks>\remeasure\zig\local'
export SCRIPTC_CC=zigcc
export SCRIPTC_TEST_CC="zig cc"
export SCRIPTC_TARGET=x86_64-windows-gnu
export SCRIPTC_TEST_WORKERS=2
export WT='<blocks>/remeasure/wt'
export LAB='<blocks>/remeasure/lab'
export ZSRC='<zapo-work>/caches/provenance/250f9af5229a545eec28ddbd3e8774a397cdb0bb'
export ZPKG="$ZSRC/packages"
export PATH="<zapo-work>/tools/zig:$PATH"
export NODE25='<home>/AppData/Local/nvm/v25.9.0'
