export ZIG_GLOBAL_CACHE_DIR='<blocks>\pkgrecheck\.zig'
export ZIG_LOCAL_CACHE_DIR='<blocks>\pkgrecheck\.zig'
export SCRIPTC_CACHE_DIR='<blocks>\pkgrecheck\.cache'
export SCRIPTC_PROVENANCE_CACHE='<blocks>\pkgrecheck-lab\prov'
export TMP='<blocks>\pkgrecheck-tmp'
export TEMP='<blocks>\pkgrecheck-tmp'
export TMPDIR='<blocks>\pkgrecheck-tmp'
export SCRIPTC_CC=zigcc
export SCRIPTC_TEST_CC='zig cc'
export SCRIPTC_TARGET=x86_64-windows-gnu
export SCRIPTC_TEST_WORKERS=3
export SCRIPTC_GENERIC_SLOT=1
export WT='<blocks>/pkgrecheck'
export LAB='<blocks>/pkgrecheck-lab'
export NODE25='<home>/AppData/Local/nvm/v25.9.0'
export PATH="<home>/AppData/Local/nvm/v25.9.0:<zapo-work>/tools/zig:/c/msys64/ucrt64/bin:/c/Program Files/Git/bin:$PATH"
