#!/bin/bash
# Regenerate every derived artefact in tests/perf/pkgstatus-0907 from the raw
# records, so nothing in the document is hand-transcribed.
. ${BLOCKS_ROOT:-<blocks>}/pkgstatus3-lab/env.sh
L=${BLOCKS_ROOT:-<blocks>}/pkgstatus3-lab
D=${BLOCKS_ROOT:-<blocks>}/pkgstatus/tests/perf/pkgstatus-0907
NAMES="store-memory store-sqlite store-mongo store-mysql store-postgres store-redis media-utils wam voip"
FNAMES="src-store-sqlite src-store-redis src-media-utils src-voip src-wam"

node "$L/table.mjs" $NAMES > "$D/table-lane-a.md"
node "$L/table.mjs" $FNAMES > "$D/table-lane-f.md"
{
  echo "# per-record site detail, generated by harness/tally.mjs"
  echo
  echo '```'
  node "$L/tally.mjs" --detail "$L/sites"
  echo '```'
} > "$D/sites-detail.txt"
{
  echo "# the shared zapo-js-core blocker cluster, generated by harness/core-cluster.mjs"
  echo
  echo '```'
  node "$L/core-cluster.mjs" store-sqlite store-mongo store-mysql store-postgres store-redis
  echo '```'
} > "$D/core-cluster.txt"
# NOTE: fences.txt is NOT regenerated here. The emitted translation units are
# 90-140 MB per program and were deleted after being counted (the volume was at
# 97%); re-running fences.sh over a pruned out/ would turn a counted 1 into
# "NO emitted TU", which is an absence, not a zero -- but it would also lose the
# byte sizes that make the count checkable. Rebuild the program first if you
# want to re-derive it.
cp "$L"/sites/*.json "$D/sites/"
cp "$L"/queue*.log "$D/logs/"
cp "$L"/out/*.build.log "$D/logs/" 2>/dev/null
cp "$L"/out/*.run.out "$L"/out/*.node.out "$D/logs/" 2>/dev/null
# Copy the harness WHOLE, every time. Copying a subset left edited scripts in
# the lab and stale ones in the repo, which is how a published harness stops
# reproducing the numbers beside it.
cp "$L"/*.sh "$L"/*.mjs "$L"/*.ps1 "$D/harness/" 2>/dev/null
cp "$L/napp/package.json" "$D/harness/napp-package.json"
cp "$L/napp/tsconfig.json" "$D/harness/napp-tsconfig.json"
cp "$L/napp/pkgsrc/tsconfig.json" "$D/harness/pkgsrc-tsconfig.json"
cp "$L/napp/pkgsrcN/tsconfig.json" "$D/harness/pkgsrcN-tsconfig.json"
cp "$L"/napp/drivers/*.ts "$L"/napp/pkgsrc/src-*.ts "$L"/napp/pkgsrcN/src-*.ts \
   "$L"/napp/hello.ts "$L"/napp/typesprobe.ts "$L"/napp/typesprobe-neg.ts "$D/drivers/" 2>/dev/null
echo "APPENDIX DONE"
ls "$D"
