#!/usr/bin/env node
/* unmask.mjs — materialize an UNMASKED copy of the bench dir.
 *
 * Three of the seventeen import `node:inspector/promises`, and the static
 * lane refuses an unsupported module BEFORE it typechecks anything. Those
 * three therefore report one diagnostic each and nothing about the other
 * eighty they would have hit. One diagnostic is not "nearly compiling"; it
 * is a gate in front of a wall nobody has seen.
 *
 * This copies the bench dir and redirects only the inspector import to a
 * local stub with the same shape. It changes NOTHING about the compiler
 * and nothing about the other 7,700 lines — it removes one gate so the
 * measurement behind it exists. The unmasked numbers are reported in their
 * own lane and never mixed with the as-given ones: `node:inspector` is a
 * real and permanent blocker for these three files (a compiled binary
 * embeds no V8 to inspect), and this does not pretend otherwise.
 *
 *   FB_APP    driver project root
 *   FB_BENCH  bench dir relative to FB_APP
 *   FB_UNMASKED_BENCH  destination, relative to FB_APP
 *                      (default: <FB_BENCH>-unmasked)
 */

import { cpSync, existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const APP = resolve(process.env.FB_APP ?? "");
const BENCH = process.env.FB_BENCH ?? "tree/packages/fake-server/bench";
const DEST = process.env.FB_UNMASKED_BENCH ?? `${BENCH}-unmasked`;

const src = join(APP, BENCH);
const dst = join(APP, DEST);
if (!existsSync(src)) {
  console.error(`unmask.mjs: no such bench dir ${src}`);
  process.exit(2);
}
rmSync(dst, { recursive: true, force: true });
cpSync(src, dst, { recursive: true });

/* The stub carries exactly the surface these three files touch:
 * connect/disconnect/on/removeListener/post.
 *
 * Two things the FIRST version got wrong, both of which made the unmasked
 * lane report FEWER sites than the masked one — a patch that looks like an
 * improvement and is really a new wall:
 *
 *  1. `on(event, fn: (...args: unknown[]) => void)` is not something a
 *     caller passing `(m: object) => void` can satisfy: `unknown` is not
 *     assignable to `object`, so every listener registration became a
 *     preflight error. Node's own typing is `(...args: any[]) => void`.
 *  2. `server-process.ts` writes `inspector.Session` in TYPE position off
 *     a DEFAULT import, which needs the module to be a namespace — which a
 *     stub with a plain class export is not. Rewriting the type reference
 *     is the honest fix; the stub is a stand-in either way. */
const STUB = `/* Generated by tests/perf/fakebench/unmask.mjs — NOT part of zapo.
 * A shape-compatible stand-in for node:inspector/promises, so the survey
 * can see what lies BEHIND the unsupported-module gate. It profiles
 * nothing. */
export class Session {
  connect(): void {}
  disconnect(): void {}
  on(_event: string, _fn: (...args: any[]) => void): void {}
  removeListener(_event: string, _fn: (...args: any[]) => void): void {}
  async post(_method: string, _params?: unknown): Promise<any> {
    return {} as any
  }
}
`;
writeFileSync(join(dst, "__inspector-stub.ts"), STUB);

let patched = 0;
const touched = [];
for (const name of readdirSync(dst)) {
  if (!name.endsWith(".ts")) continue;
  const p = join(dst, name);
  const before = readFileSync(p, "utf8");
  /* The whole import declaration goes, both spellings (`import * as
   * inspector` and the default `import inspector`), and every
   * `inspector.Session` — type position included — becomes the named
   * class. Nothing else in the file is touched. */
  const after = before
    .replace(
      /^[ \t]*import\s+(?:\*\s+as\s+)?inspector\s+from\s+(['"])node:inspector\/promises\1[ \t]*$/gm,
      "import { Session as InspectorSession } from './__inspector-stub'",
    )
    .replace(/\binspector\.Session\b/g, "InspectorSession");
  if (after !== before) {
    writeFileSync(p, after);
    patched++;
    touched.push(name);
  }
}

/* Positive control: the patch must have fired, and the phrase it removed
 * must be gone. A silent no-op copy would produce an "unmasked" lane
 * identical to the masked one and nobody would know why. */
/* Only a quoted SPECIFIER counts as a leftover. The phrase also appears in
 * prose — messaging.bench.ts documents its profiler wrapper, and the stub's
 * own header says what it stands in for — and a check that cannot tell a
 * comment from an import fails on a tree that is completely patched. */
const leftovers = readdirSync(dst).filter(
  (n) =>
    n.endsWith(".ts") &&
    /(['"])node:inspector(\/promises)?\1/.test(readFileSync(join(dst, n), "utf8")),
);
console.log(`unmasked ${DEST}: patched ${patched} file(s) [${touched.join(", ")}], leftovers ${leftovers.length}`);
if (patched === 0 || leftovers.length > 0) {
  console.error("unmask.mjs: PATCH DID NOT FIRE CLEANLY — refusing to claim an unmasked tree.");
  process.exit(3);
}
