#!/usr/bin/env node
/* unmask.mjs — materialize an UNMASKED copy of the bench dir.
 *
 * Three of the seventeen import `node:inspector/promises`, and the static
 * lane refuses an unsupported module BEFORE it typechecks anything. Those
 * three therefore report one diagnostic each and nothing about the other
 * eighty they would have hit. One diagnostic is not "nearly compiling"; it
 * is a gate in front of a wall nobody has seen.
 *
 * This copies the bench dir and redirects only the inspector import to a
 * local stub with the same shape. It changes NOTHING about the compiler
 * and nothing about the other 7,700 lines — it removes one gate so the
 * measurement behind it exists. The unmasked numbers are reported in their
 * own lane and never mixed with the as-given ones: `node:inspector` is a
 * real and permanent blocker for these three files (a compiled binary
 * embeds no V8 to inspect), and this does not pretend otherwise.
 *
 *   FB_APP    driver project root
 *   FB_BENCH  bench dir relative to FB_APP
 *   FB_UNMASKED_BENCH  destination, relative to FB_APP
 *                      (default: <FB_BENCH>-unmasked)
 */

import { cpSync, existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const APP = resolve(process.env.FB_APP ?? "");
const BENCH = process.env.FB_BENCH ?? "tree/packages/fake-server/bench";
const DEST = process.env.FB_UNMASKED_BENCH ?? `${BENCH}-unmasked`;

const src = join(APP, BENCH);
const dst = join(APP, DEST);
if (!existsSync(src)) {
  console.error(`unmask.mjs: no such bench dir ${src}`);
  process.exit(2);
}
rmSync(dst, { recursive: true, force: true });
cpSync(src, dst, { recursive: true });

/* The stub carries exactly the surface these three files touch: `Session`
 * with connect/disconnect/on/removeListener/post, as both a named and a
 * default export (server-process.ts default-imports the module). */
const STUB = `/* Generated by tests/perf/fakebench/unmask.mjs — NOT part of zapo.
 * A shape-compatible stand-in for node:inspector/promises, so the survey
 * can see what lies BEHIND the unsupported-module gate. It profiles
 * nothing. */
export class Session {
  connect(): void {}
  disconnect(): void {}
  on(_event: string, _fn: (...args: unknown[]) => void): void {}
  removeListener(_event: string, _fn: (...args: unknown[]) => void): void {}
  async post(_method: string, _params?: unknown): Promise<any> {
    return {} as any
  }
}
export default { Session }
`;
writeFileSync(join(dst, "__inspector-stub.ts"), STUB);

let patched = 0;
const touched = [];
for (const name of readdirSync(dst)) {
  if (!name.endsWith(".ts")) continue;
  const p = join(dst, name);
  const before = readFileSync(p, "utf8");
  const after = before.replace(
    /(['"])node:inspector\/promises\1/g,
    "'./__inspector-stub'",
  );
  if (after !== before) {
    writeFileSync(p, after);
    patched++;
    touched.push(name);
  }
}

/* Positive control: the patch must have fired, and the phrase it removed
 * must be gone. A silent no-op copy would produce an "unmasked" lane
 * identical to the masked one and nobody would know why. */
const leftovers = readdirSync(dst).filter(
  (n) => n.endsWith(".ts") && /node:inspector/.test(readFileSync(join(dst, n), "utf8")),
);
console.log(`unmasked ${DEST}: patched ${patched} file(s) [${touched.join(", ")}], leftovers ${leftovers.length}`);
if (patched === 0 || leftovers.length > 0) {
  console.error("unmask.mjs: PATCH DID NOT FIRE CLEANLY — refusing to claim an unmasked tree.");
  process.exit(3);
}
