// set / subarray / slice / fill / iteration / spread / instanceof.
const a = new Int16Array([10, 20, 30, 40])
console.log(a instanceof Int16Array, a instanceof Uint16Array, a instanceof Uint8Array)
const s = a.subarray(1, 3)
console.log('sub', s.length, s.byteLength, s[0], s[1])
const sl = a.slice(1, 3)
console.log('slice', sl.length, sl.byteLength, sl[0], sl[1])
a.fill(-7)
console.log('fill', a[0], a[1], a[2], a[3])
const b = new Int16Array(4)
b.set(a, 0)
console.log('set', b[0], b[3])
for (const v of b) console.log('it', v)
console.log('spread', [...b].join(','))
const u = new Uint16Array([1, 2, 3])
console.log('u16 inst', u instanceof Uint16Array, u instanceof Int16Array)
