/* Part 3 of 8 of the coverage corpus sweep. GENERATED by
 * scripts/gen-corpus-parts.mjs — do not edit by hand, and do not delete one:
 * corpus-parts.test.ts fails when the set here stops being exactly 1..N. */
import { defineCoverageCorpusSweep } from "../coverage-corpus-suite.js";

defineCoverageCorpusSweep(3, 8);
