/* Part 3 of 8 of the corpus differential. GENERATED by
 * scripts/gen-corpus-parts.mjs — do not edit by hand, and do not delete one:
 * corpus-parts.test.ts fails when the set here stops being exactly 1..N. */
import { defineDifferentialSuite } from "../differential-suite.js";

defineDifferentialSuite(3, 8);
