/* Part 2 of 8 of the dual-backend differential. GENERATED by
 * scripts/gen-corpus-parts.mjs — do not edit by hand, and do not delete one:
 * corpus-parts.test.ts fails when the set here stops being exactly 1..N. */
import { defineLlvmDifferentialSuite } from "../llvm-differential-suite.js";

defineLlvmDifferentialSuite(2, 8);
