export ZIG_GLOBAL_CACHE_DIR='<blocks>\pkgstatus\.zig'
export ZIG_LOCAL_CACHE_DIR='<blocks>\pkgstatus\.zig'
export SCRIPTC_CACHE_DIR='<blocks>\pkgstatus\.cache'
export SCRIPTC_PROVENANCE_CACHE='<blocks>\pkgstatus-lab\prov'
export TMP='<blocks>\pkgstatus-tmp'
export TEMP='<blocks>\pkgstatus-tmp'
export TMPDIR='<blocks>\pkgstatus-tmp'
export SCRIPTC_CC=zigcc
export SCRIPTC_TEST_CC='zig cc'
export SCRIPTC_TARGET=x86_64-windows-gnu
export SCRIPTC_TEST_WORKERS=4
export SCRIPTC_GENERIC_SLOT=1
export WT='<blocks>/pkgstatus'
export LAB='<blocks>/pkgstatus-lab'
export ZSRC='<zapo-work>/caches/provenance/250f9af5229a545eec28ddbd3e8774a397cdb0bb'
export ZPKG="$ZSRC/packages"
export PATH="<zapo-work>/tools/zig:$PATH"
export NODE25='<home>/AppData/Local/nvm/v25.9.0'
