export ZIG_GLOBAL_CACHE_DIR='G:\blocks\voipfix\.zig'
export ZIG_LOCAL_CACHE_DIR='G:\blocks\voipfix\.zig'
export SCRIPTC_CACHE_DIR='G:\blocks\voipfix\.cache'
export SCRIPTC_PROVENANCE_CACHE='G:\blocks\pkgstatus-lab\prov'
export TMP='G:\blocks\voipfix-tmp'
export TEMP='G:\blocks\voipfix-tmp'
export TMPDIR='G:\blocks\voipfix-tmp'
export SCRIPTC_CC=zigcc
export SCRIPTC_TEST_CC='zig cc'
export SCRIPTC_TARGET=x86_64-windows-gnu
export SCRIPTC_TEST_WORKERS=3
export SCRIPTC_GENERIC_SLOT=1
export WT='G:/blocks/voipfix'
export LAB='G:/blocks/voipfix-lab'
export ZSRC='G:/zapo-work/caches/provenance/250f9af5229a545eec28ddbd3e8774a397cdb0bb'
export ZPKG="$ZSRC/packages"
export PATH="/g/zapo-work/tools/zig:$PATH"
export NODE25='/c/Users/vinicius/AppData/Local/nvm/v25.9.0'
